name: Execução de testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sum-testes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chackout testes
        uses: actions/chackout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependences
        run: 
          npm install express
          npm install
        
      - name: Run sumJS teste
        run: npm start
